"""Paratro MPC Wallet SDK for Python."""

from importlib.metadata import PackageNotFoundError, version as _pkg_version

from paratro.client import DEFAULT_TIMEOUT, MPCClient
from paratro.config import Config
from paratro.errors import (
    APIError,
    AuthenticationError,
    BadRequestError,
    ConflictError,
    EndpointRetiredError,
    ErrorCode,
    ErrorType,
    ForbiddenError,
    NotFoundError,
    RateLimitError,
    RejectedError,
    RejectionReason,
    ServiceUnavailableError,
    is_auth_error,
    is_endpoint_retired,
    is_engine_busy,
    is_forbidden,
    is_not_found,
    is_rate_limited,
    is_rejected,
    is_service_unavailable,
    is_token_expired,
)
from paratro.models import (
    Account,
    Asset,
    ContractCall,
    ContractCallIncomingLeg,
    ContractCallOutgoingLeg,
    ContractCallRequest,
    CreateAccountRequest,
    CreateAssetRequest,
    CreateTransactionResponse,
    CreateTransferRequest,
    CreateWalletRequest,
    ListAccountsRequest,
    ListAssetsRequest,
    ListTransactionsRequest,
    ListWalletsRequest,
    ListX402SettlementsRequest,
    Operation,
    PaginatedResponse,
    ProgramCallRequest,
    Transaction,
    TransactionStatus,
    TransferRequest,
    TransferResponse,
    Wallet,
    WebhookEvent,
    WebhookEventType,
    X402Settlement,
    X402SettleResponse,
    X402SettleStatusResponse,
    X402VerifyResponse,
)
from paratro.transactions import TransactionsService
from paratro.webhook import parse_event, verify_signature
from paratro.x402 import X402Service

try:
    __version__ = _pkg_version("paratro-sdk")
except PackageNotFoundError:  # pragma: no cover
    __version__ = "0.0.0"

__all__ = [
    "MPCClient",
    "Config",
    "DEFAULT_TIMEOUT",
    # errors
    "APIError",
    "AuthenticationError",
    "BadRequestError",
    "ConflictError",
    "EndpointRetiredError",
    "ErrorCode",
    "ErrorType",
    "ForbiddenError",
    "NotFoundError",
    "RateLimitError",
    "RejectedError",
    "RejectionReason",
    "ServiceUnavailableError",
    "is_auth_error",
    "is_endpoint_retired",
    "is_engine_busy",
    "is_forbidden",
    "is_not_found",
    "is_rate_limited",
    "is_rejected",
    "is_service_unavailable",
    "is_token_expired",
    # models
    "Account",
    "Asset",
    "ContractCall",
    "ContractCallIncomingLeg",
    "ContractCallOutgoingLeg",
    "ContractCallRequest",
    "CreateAccountRequest",
    "CreateAssetRequest",
    "CreateTransactionResponse",
    "CreateTransferRequest",
    "CreateWalletRequest",
    "ListAccountsRequest",
    "ListAssetsRequest",
    "ListTransactionsRequest",
    "ListWalletsRequest",
    "ListX402SettlementsRequest",
    "Operation",
    "PaginatedResponse",
    "ProgramCallRequest",
    "Transaction",
    "TransactionStatus",
    "TransferRequest",
    "TransferResponse",
    "Wallet",
    "WebhookEvent",
    "WebhookEventType",
    "X402Settlement",
    "X402SettleResponse",
    "X402SettleStatusResponse",
    "X402VerifyResponse",
    # services
    "TransactionsService",
    "X402Service",
    # webhook
    "verify_signature",
    "parse_event",
    "__version__",
]
